- alias: Set dark theme at startup and login
  description: 'This automation sets the HomeAssistant UI to a dark theme.'
  trigger: 
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: simple-dark

# - alias: TravisCI
  #description: 'When a TravisCI build completes with a Pass, that build is pulled from GitHub to HomeAssistant, and the instance is restarted for new configurations to be run.'
  #trigger:
    #- platform: state
      #entity_id: 
  #condition:
    #- condition: state
      #entity_id: 
      #state: 'passed'
  #action:   
    #- service: hassio.addon_start
      #data: 
        #addon: "core_git_pull"

- alias: Outdoor Lights at Sundown
  description: 'This automation controls the outdoor lights to turn on shortly before sundown.'
  trigger:
  - event: sunset
    offset: -0:15
    platform: sun
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_lights

- alias: Outdoor Lights Off Morning
  description: 'This automation will turn the lights off shortly before sunrise.'
  trigger:
    event: sunrise
    offset: -0:15
    platform: sun
  condition:
    condition: state
    entity_id: group.outdoor_lights
    state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: group.outdoor_lights

- alias: DaDaLights On
  description: 'This automation will control the lights when teaching DaDa in the morning'
  trigger:
    platform: time
    at: '05:45:00' 
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    #- service: light.turn_on
     # data:
      #  entity_id: light.master_bedroom_hallway_1
      #  brightness_pct: 50
      #  transition: 5
    #- service: light.turn_on
      #data:
        #entity_id: light.light.2nd_floor_hall_1
        #brightness_pct: 50
        #transition: 5
    - service: light.turn_on
      data:
        entity_id: light.living_room_1
        brightness_pct: 100
        transition: 5
    #- service: light.turn_on
     # data:
      #  entity_id: light.master_bath_shower
      #  brightness_pct: 50
      #  transition: 5
    #- service: light.turn_on
     # data:
      #  entity_id: light.johni_s_office
      #  brightness_pct: 50
      #  transition: 5
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_cabinet_all

- alias: DaDaLights Off
  description: 'This automation will control the lights for when teaching DaDa is over.'
  trigger:
    platform: time
    at: '08:50:00' 
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: homeassistant.turn_off
      data:
      - entity_id: group.johni_s_office
        transition: 5

- alias: Basement Lights On
  description: 'This automation will turn on all Basement lights if the Basement Hallway is lit'
  trigger:
    platform: state
    entity_id: switch.basement_hall_2
    from: 'off'
    to: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.basement
        transition: 5