- alias: Set dark theme at startup and login
  description: 'This automation sets the HomeAssistant UI to a dark theme.'
  trigger: 
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: simple-dark

# - alias: TravisCI
  #description: 'When a TravisCI build completes with a Pass, that build is pulled from GitHub to HomeAssistant, and the instance is restarted for new configurations to be run.'
  #trigger:
    #- platform: state
      #entity_id: 
  #condition:
    #- condition: state
      #entity_id: 
      #state: 'passed'
  #action:   
    #- service: hassio.addon_start
      #data: 
        #addon: "core_git_pull"

- alias: Outdoor Lights at Sundown
  description: 'This automation controls the outdoor lights to turn on 15 min before sundown.'
  trigger:
  - event: sunset
    offset: -0:15
    platform: sun
  action:
  - data:
      entity_id: switch.outdoor_lights
    service: switch.turn_on

- alias: Outdoor Lights Off Morning
  description: 'This automation will turn the lights off shortly before sunrise.'
  trigger:
    event: sunrise
    offset: -0:15
    platform: sun
  condition:
    condition: state
    entity_id: switch.outdoor_lights
    state: 'off'
  action:
    entity_id: switch.outdoor_lights
    service: switch.turn_off

- alias: Johni DaDaLights On
  description: 'This automation will control the lights for when Johni goes to teach DaDa in the morning'
  trigger:
    platform: time
    at: '05:45:00' 
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom_hallway_1
        brightness_pct: 50
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.light.2nd_floor_hall_1
        brightness_pct: 50
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.living_room_1
        brightness_pct: 50
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.master_bath_shower
        brightness_pct: 50
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.johni_s_office
        brightness_pct: 50
        transition: 5
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_cabinet_all

- alias: Johni DaDaLights Off
  description: 'This automation will control the lights for when Johni is done teaching DaDa.'
  trigger:
    platform: time
    at: '08:45:00' 
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: light.turn_off
      data:
        entity_id: light.master_bedroom_hallway_1s
        transition: 5
    - service: light.turn_off
      data:
        entity_id: light.light.2nd_floor_hall_1
        transition: 5
    - service: light.turn_off
      data:
        entity_id: light.living_room_1
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.master_bath_shower
        transition: 5
    - service: light.turn_off
      data:
        entity_id: light.johni_s_office
        transition: 5
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_cabinet_all  