title: Lighthouse Rock
views:
  ################
  ### Main tab ###
  ################

  - path: default_view
    title: Main
    badges:
      - device_tracker.ricardo_8d620d94_fed2_48dc_baf4_d268cd78cd15
      - sensor.ring_front_door_last_ding
      - sensor.ring_front_door_last_motion
      - sensor.ring_front_door_battery
      - binary_sensor.updater
      - binary_sensor.workday_sensor
    cards:
      - type: picture-entity
        entity: camera.front_door
      - type: weather-forecast
        entity: weather.lighthouse_rock

##################
### Lights tab ###
##################
  - path: lights
    title: Lights
    # badges:
    cards:
      - type: entities
        entities:
          - light.basement_1
          - light.basement_2
          - light.basement_aux
          - switch.basement_hall_1
          - switch.basement_hall_2
        title: Basement
        show_header_toggle: true
      - type: entities
        entities:
          - light.living_room_1
          - light.living_room_2
          - switch.living_room_sconces
          - light.kitchen_1
          - light.kitchen_2
          - light.kitchen_dr_window
          - light.kitchen_over_back_sink
          - light.kitchen_over_side_sink
          - switch.kitchen_cabinet_oven_side
          - switch.kitchen_cabinet_dr_window
          - light.pantry_hall_1
          - light.pantry_hall_2
          - light.dining_room_1
          - light.dining_room_2
          - light.master_bedroom
          - light.master_bedroom_hallway_1
          - light.master_bedroom_hallway_2
          - light.master_bathroom_1_keypad
          - light.master_bathroom_2
          - light.master_bath_vanity
          - light.master_bath_shower
          - switch.master_bathroom_fan
        title: First Floor
        show_header_toggle: true
      - type: entities
        entities:
          - light.2nd_floor_hall_1
          - light.2nd_floor_hall_3
          - light.2nd_floor_bathroom
          - light.2nd_floor_bathroom_shower
          - light.2nd_floor_bathroom_vanity
          - switch.2nd_floor_bathroom_fan
          - light.2nd_floor_back_bedroom
          - light.2nd_floor_front_bedroom
          - light.johni_s_office
        title: Second Floor
        show_header_toggle: true
      - type: entities
        entities:
          - light.attic_1
          - light.attic_2
        title: Attic
        show_header_toggle: true
      - type: entities
        entities:
          - switch.kitchen_cabinet_oven_side
          - switch.kitchen_cabinet_dr_window
          - light.master_bedroom_hallway_1
        title: Night Light
        show_header_toggle: true

#######################
### Automations tab ###
#######################

  - path: automation
    cards:
      - type: entities
        entities:
          - automation.set_dark_theme_at_startup_and_login
          - automation.outdoor_lights_at_sundown
          - automation.outdoor_lights_off_morning
          - automation.johni_dadalights_on
          - automation.johni_dadalights_off
        title: Automations